package org.ccrew.cchess.lib;

public enum ChessRule {
    UNKNOWN, CHECKMATE, STALEMATE, FIFTY_MOVES, SEVENTY_FIVE_MOVES, TIMEOUT, THREE_FOLD_REPETITION,
    FIVE_FOLD_REPETITION, INSUFFICIENT_MATERIAL, RESIGN, ABANDONMENT, DEATH, BUG
}
